#' Input data from CPP output into a set of R data frames
#' @param filename The filename of the output generated by the simulation
#' @export
parseSimulationOutput <- function(filename)
{
  # TODO: Return a good error message if the file cannot be parsed
  data <- list()
  # TODO: extract parameters and store in the same dataframe
  data$params <- c()
  data$sequences <- data.frame()
  data$pairwise <- data.frame()

  con = file(filename, "r")

  # basic variables
  t <- -1
  realTime <- -1
  tags <- NULL

  while (TRUE)
  {
    # try and extract the next block of data
    next_line = extract_line(con)

    if (length(next_line) == 0) # end of file
    {
      break
    }
    if (next_line[1] == "0") # header info
    {
      next
    }
    if (next_line[1] == "@")
    {
      # First, get the time
      time_line <- as.numeric(extract_line(con))
      t <- time_line[1]
      realTime <- time_line[2]

      # Get which things are going to be output
      which_output_line <- as.numeric(extract_line(con))
      to_tags <- which_output_line[1]
      to_init <- which_output_line[2]
      to_seqs <- which_output_line[3]
      to_pair <- which_output_line[4]

      family_line <- extract_line(con)
      stopifnot(family_line[1] == "F")
      family_line <- extract_line(con)
      num_families <- as.numeric(family_line[1])

      # To store the tags in memory
      speciesIds <- integer(num_families)
      previousSpeciesId_tags <- integer(num_families)
      sequenceIds <- list()

      if (num_families == 0)
      {
        if (to_pair)
        {
          pairs_line <- extract_line(con)
          stopifnot(pairs_line[1] == "P")
          blank_line <- extract_line(con)
        }
        next
      }

      # For each family, parse all the data
      for (fam_i in 1:num_families)
      {
        family_tag_line <- extract_line(con)
        speciesIds[fam_i] <- as.numeric(family_tag_line)[1]
        previousSpeciesId_tags[fam_i] <- as.numeric(family_tag_line)[2]

        tags_line <- extract_line(con)

        stopifnot(tags_line[1] == "T")
        tags_line <- extract_line(con)
        num_seqs <- tags_line[1]
        all_seqs <- extract_line(con)

        # Extract sequence tag data
        sequenceIds[[fam_i]] <- integer(num_seqs)
        parentMain <- integer(num_seqs)
        parentOther <- integer(num_seqs)
        isActive <- logical(num_seqs)

        for (seq_i in 1:num_seqs)
        {
          parsed_seq <- strsplit(
                          gsub("\\*|\\)|\\(|-|\\/", " ", all_seqs[seq_i]),
                          " ")[[1]]
          sequenceIds[[fam_i]][seq_i] <- as.numeric(parsed_seq[1])

          # Make -1 denote initial sequence
          if (parsed_seq[3] == "I" || parsed_seq[3] == "R")
          {
             parentMain[seq_i] <- -1
             parentOther[seq_i] <- -1
          }
          else
          {
             parentMain[seq_i] <- as.numeric(parsed_seq[3])
             parentOther[seq_i] <- as.numeric(parsed_seq[4])
          }
          isActive[seq_i] <- stringr::str_detect(all_seqs[seq_i], "\\*")
        }

        if (to_init)
        {
          init_line <- extract_line(con)
          stopifnot(init_line[1] == "I")
          # Extract distance to initial sequence
          init_line <- extract_line(con)
          distanceToInitials <- as.numeric(init_line)
          for (seq_i in 1:num_seqs)
          {
            row <- list(step=t, realTime=realTime,
                        sequenceId=sequenceIds[[fam_i]][seq_i],
                        speciesId=speciesIds[fam_i], previousSpeciesId=previousSpeciesId_tags[fam_i],
                        parentMain=parentMain[seq_i], parentOther=parentOther[seq_i], isActive=isActive[seq_i],
                        distanceToInitial=distanceToInitials[seq_i],
                        rawSequence=NA)
            data$sequences <- rbind(data$sequences, row)
          }
        }

        if (to_seqs)
        {
          seqs_line <- extract_line(con)
          stopifnot(seqs_line[1] == "S")
          # Extract raw sequence
          for (seq_i in 1:num_seqs)
          {
            rawSequence <- extract_line(con)
            found <- which(data$sequences$step == t & data$sequences$sequenceId==sequenceIds[[fam_i]][seq_i],
                           arr.ind = TRUE)
            data$sequences[found, ]$rawSequence  <- rawSequence
          }
        }
      } # End 'for each family'

      if (to_pair)
      {
        pairs_line <- extract_line(con)
        stopifnot(pairs_line[1] == "P")
        # Pairwise distances
        pairs <- as.numeric(extract_line(con))
        nrows <- length(pairs)
        steps <- rep(t, nrows)
        realTimes <- rep(realTime, nrows)
        sequenceId1s <- rep(NA, nrows)
        sequenceId2s <- rep(NA, nrows)

        count <- 1
        f1 <- 1 # Family F1
        while (f1 <= length(speciesIds))
        {
          s1 <- 1 # Sequence S1
          while (s1 <= length(sequenceIds[[f1]]))
          {
            s2 <- s1 + 1 # Sequence S2 in F1
            while (s2 <= length(sequenceIds[[f1]]))
            {
              sequenceId1s[count] <- sequenceIds[[f1]][s1]
              sequenceId2s[count] <- sequenceIds[[f1]][s2]
              count <- count + 1
              s2 <- s2 + 1
            }

            f2 <- f1 + 1 # Family F2
            while (f2 <= length(speciesIds))
            {
              s2 <- 1 # Sequence S2 in F2
              while (s2 <= length(sequenceIds[[f2]]))
              {
                sequenceId1s[count] <- sequenceIds[[f1]][s1]
                sequenceId2s[count] <- sequenceIds[[f2]][s2]
                count <- count + 1
                s2 <- s2 + 1
              }
              f2 <- f2 + 1
            } # end <for family F2>
            s1 <- s1 + 1
          }
          f1 <- f1 + 1
        } # end <for family F1>

        data$pairwise <- rbind(data$pairwise,
                           data.frame(step=steps,realTime=realTimes,
                                      sequenceId1=sequenceId1s, sequenceId2=sequenceId2s,
                                      distancePairwise=pairs) %>%
                           dplyr::mutate(sequenceId1 = pmin(sequenceId1, sequenceId2),
                                         sequenceId2 = pmax(sequenceId1, sequenceId2)
                           )
        )

      } # end <extract pair data>
    } # end <for this timestamp>
    else
    {
        stop(paste("Unknown letter in file", next_line[2]))
    }
  } # end <for this file>

  close(con)

  return(data)
}

# To extract the next line from the file
extract_line <- function(in_file)
{
  line = readLines(in_file, n=1)
  if (length(line) == 0) { return(c()) }
  return(strsplit(line, " ")[[1]])
}

