# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
test_main <- function() {
    .Call('_rcombinator_test_main', PACKAGE = 'rcombinator')
}

#' @export
test_other <- function() {
    .Call('_rcombinator_test_other', PACKAGE = 'rcombinator')
}

#' @export
test_new <- function() {
    .Call('_rcombinator_test_new', PACKAGE = 'rcombinator')
}

